/*
 * generated by Xtext 2.18.0.M3
 */
package uk.ac.kcl.inf.gts_morpher.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GTSMorpherUiModule extends AbstractGTSMorpherUiModule {
}
