<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="server" nsURI="http://server/1.0" nsPrefix="server">
  <eClassifiers xsi:type="ecore:EClass" name="Server">
    <eAnnotations source="Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Out" upperBound="-1" eType="#//Queue">
      <eAnnotations source="Interface"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="In" upperBound="-1" eType="#//Queue">
      <eAnnotations source="Interface"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Queue">
    <eAnnotations source="Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elts" upperBound="-1" eType="#//Element">
      <eAnnotations source="Interface"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="Interface"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eAnnotations source="Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//Element">
    <eAnnotations source="Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//Element">
    <eAnnotations source="Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerObserver">
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
        eType="#//Server"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produced" upperBound="-1"
        eType="#//Element"/>
  </eClassifiers>
</ecore:EPackage>
