/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.gts_morpher

import org.eclipse.xtext.conversion.impl.INTValueConverter
import uk.ac.kcl.inf.gts_morpher.util.MyINTValueConverter

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GTSMorpherRuntimeModule extends AbstractGTSMorpherRuntimeModule {
	
	def Class<? extends INTValueConverter> bindINTValueConverter() { MyINTValueConverter }
}
