<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="devsmm" nsURI="http://devsmm/1.0" nsPrefix="devsmm">
  <eClassifiers xsi:type="ecore:EClass" name="Machine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pt" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defective_rate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="in" eType="#//Tray"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" lowerBound="1" eType="#//Conveyor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generator" eSuperTypes="#//Machine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenHead" eSuperTypes="#//Generator"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenHandle" eSuperTypes="#//Generator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assemble" eSuperTypes="#//Machine"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="#//Part" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tray" eSuperTypes="#//LimitedContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Container"/>
  <eClassifiers xsi:type="ecore:EClass" name="Conveyor" eSuperTypes="#//LimitedContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="out" lowerBound="1" eType="#//Tray"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outParts" upperBound="-1"
        eType="#//Part" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LimitedContainer" eSuperTypes="#//Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Part">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defective" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Head" eSuperTypes="#//Part"/>
  <eClassifiers xsi:type="ecore:EClass" name="Handle" eSuperTypes="#//Part"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hammer" eSuperTypes="#//Part"/>
</ecore:EPackage>
