/*
 * generated by Xtext 2.18.0.M3
 */
package uk.ac.kcl.inf.gts_morpher.ide


/**
 * Use this class to register ide components.
 */
class GTSMorpherIdeModule extends AbstractGTSMorpherIdeModule {
}
