/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XDsmlComposeStandaloneSetup extends XDsmlComposeStandaloneSetupGenerated {

	def static void doSetup() {
		new XDsmlComposeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
