<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="A_B" nsURI="https://metamodel.woven/a/a/b" nsPrefix="a_b">
  <eClassifiers xsi:type="ecore:EClass" name="A1_B1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left__bs" upperBound="-1"
        eType="#//left__A2" containment="true" eOpposite="#//left__A2/left__a"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right__bs" upperBound="-1"
        eType="#//right__B2" containment="true" eOpposite="#//right__B2/right__a"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="left__A2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left__a" eType="#//A1_B1"
        changeable="false" eOpposite="#//A1_B1/left__bs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="right__B2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right__a" eType="#//A1_B1"
        changeable="false" eOpposite="#//A1_B1/right__bs"/>
  </eClassifiers>
</ecore:EPackage>
