<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="A_B_A0" nsURI="https://metamodel.woven/a/b/a0" nsPrefix="a_b_a0">
  <eClassifiers xsi:type="ecore:EClass" name="A1_B1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source__bs" upperBound="-1"
        eType="#//source__A2" containment="true" eOpposite="#//source__A2/source__a"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target__bs" upperBound="-1"
        eType="#//target__B2" containment="true" eOpposite="#//target__B2/target__a"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="source__A2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source__a" eType="#//A1_B1"
        changeable="false" eOpposite="#//A1_B1/source__bs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="target__B2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target__a" eType="#//A1_B1"
        changeable="false" eOpposite="#//A1_B1/target__bs"/>
  </eClassifiers>
</ecore:EPackage>
