<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="A5_B4" nsURI="https://metamodel.woven/a5/a5/b4" nsPrefix="a5_b4">
  <eClassifiers xsi:type="ecore:EClass" name="A1_B1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numA_numB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="left__numA2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="left__A2"/>
</ecore:EPackage>
