<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="B" nsURI="http://kcl.ac.uk/xdsml/B" nsPrefix="b">
  <eClassifiers xsi:type="ecore:EClass" name="B1">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bs" upperBound="-1" eType="#//B2"
        containment="true" eOpposite="#//B2/a"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="a" eType="#//B1" changeable="false"
        eOpposite="#//B1/bs"/>
  </eClassifiers>
</ecore:EPackage>
